//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 02:09:18 PM GMT 
//


package is.hi.vinnsla;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allarStodvar">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vedurstod" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="atime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="err" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="spaStodvar">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="vedurspa" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="D" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="F" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="R" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                 &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="TD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="W" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ftime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allarStodvar"
})
@XmlRootElement(name = "nidurstodur")
public class Nidurstodur {

    @XmlElement(required = true)
    protected Nidurstodur.AllarStodvar allarStodvar;

    /**
     * Gets the value of the allarStodvar property.
     * 
     * @return
     *     possible object is
     *     {@link Nidurstodur.AllarStodvar }
     *     
     */
    public Nidurstodur.AllarStodvar getAllarStodvar() {
        return allarStodvar;
    }

    /**
     * Sets the value of the allarStodvar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nidurstodur.AllarStodvar }
     *     
     */
    public void setAllarStodvar(Nidurstodur.AllarStodvar value) {
        this.allarStodvar = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="vedurstod" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="atime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="err" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="spaStodvar">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="vedurspa" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="D" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="F" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="R" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                                       &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="TD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="W" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ftime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vedurstod"
    })
    public static class AllarStodvar {

        protected List<Nidurstodur.AllarStodvar.Vedurstod> vedurstod;

        /**
         * Gets the value of the vedurstod property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vedurstod property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVedurstod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nidurstodur.AllarStodvar.Vedurstod }
         * 
         * 
         */
        public List<Nidurstodur.AllarStodvar.Vedurstod> getVedurstod() {
            if (vedurstod == null) {
                vedurstod = new ArrayList<Nidurstodur.AllarStodvar.Vedurstod>();
            }
            return this.vedurstod;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="atime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="err" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="spaStodvar">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="vedurspa" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="D" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="F" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="R" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *                             &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="TD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="W" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ftime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "atime",
            "err",
            "spaStodvar",
            "id",
            "link",
            "name",
            "valid"
        })
        public static class Vedurstod {

            @XmlElement(required = true)
            protected String atime;
            @XmlElement(required = true)
            protected String err;
            @XmlElement(required = true)
            protected Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar spaStodvar;
            protected short id;
            @XmlElement(required = true)
            @XmlSchemaType(name = "anyURI")
            protected String link;
            @XmlElement(required = true)
            protected String name;
            protected byte valid;

            /**
             * Viðótar aðferð til að ná í lýsingu á veðurstöð
             * @return 
             */
            @Override 
            public String toString() {
                return name;
            }
            /**
             * Gets the value of the atime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAtime() {
                return atime;
            }

            /**
             * Sets the value of the atime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAtime(String value) {
                this.atime = value;
            }

            /**
             * Gets the value of the err property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getErr() {
                return err;
            }

            /**
             * Sets the value of the err property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setErr(String value) {
                this.err = value;
            }

            /**
             * Gets the value of the spaStodvar property.
             * 
             * @return
             *     possible object is
             *     {@link Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar }
             *     
             */
            public Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar getSpaStodvar() {
                return spaStodvar;
            }

            /**
             * Sets the value of the spaStodvar property.
             * 
             * @param value
             *     allowed object is
             *     {@link Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar }
             *     
             */
            public void setSpaStodvar(Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar value) {
                this.spaStodvar = value;
            }

            /**
             * Gets the value of the id property.
             * 
             */
            public short getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(short value) {
                this.id = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLink(String value) {
                this.link = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the valid property.
             * 
             */
            public byte getValid() {
                return valid;
            }

            /**
             * Sets the value of the valid property.
             * 
             */
            public void setValid(byte value) {
                this.valid = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="vedurspa" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="D" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="F" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="R" type="{http://www.w3.org/2001/XMLSchema}float"/>
             *                   &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="TD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="W" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ftime" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "vedurspa"
            })
            public static class SpaStodvar {

                protected List<Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar.Vedurspa> vedurspa;

                /**
                 * Gets the value of the vedurspa property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the vedurspa property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getVedurspa().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar.Vedurspa }
                 * 
                 * 
                 */
                public List<Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar.Vedurspa> getVedurspa() {
                    if (vedurspa == null) {
                        vedurspa = new ArrayList<Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar.Vedurspa>();
                    }
                    return this.vedurspa;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="D" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="F" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="N" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="R" type="{http://www.w3.org/2001/XMLSchema}float"/>
                 *         &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="TD" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="W" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ftime" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "d",
                    "f",
                    "n",
                    "r",
                    "t",
                    "td",
                    "w",
                    "ftime"
                })
                public static class Vedurspa {

                    @XmlElement(name = "D", required = true)
                    protected String d;
                    @XmlElement(name = "F")
                    protected byte f;
                    @XmlElement(name = "N")
                    protected byte n;
                    @XmlElement(name = "R")
                    protected float r;
                    @XmlElement(name = "T")
                    protected byte t;
                    @XmlElement(name = "TD")
                    protected byte td;
                    @XmlElement(name = "W", required = true)
                    protected String w;
                    @XmlElement(required = true)
                    protected String ftime;

                    /**
                     * Gets the value of the d property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getD() {
                        return d;
                    }

                    /**
                     * Sets the value of the d property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setD(String value) {
                        this.d = value;
                    }

                    /**
                     * Gets the value of the f property.
                     * 
                     */
                    public byte getF() {
                        return f;
                    }

                    /**
                     * Sets the value of the f property.
                     * 
                     */
                    public void setF(byte value) {
                        this.f = value;
                    }

                    /**
                     * Gets the value of the n property.
                     * 
                     */
                    public byte getN() {
                        return n;
                    }

                    /**
                     * Sets the value of the n property.
                     * 
                     */
                    public void setN(byte value) {
                        this.n = value;
                    }

                    /**
                     * Gets the value of the r property.
                     * 
                     */
                    public float getR() {
                        return r;
                    }

                    /**
                     * Sets the value of the r property.
                     * 
                     */
                    public void setR(float value) {
                        this.r = value;
                    }

                    /**
                     * Gets the value of the t property.
                     * 
                     */
                    public byte getT() {
                        return t;
                    }

                    /**
                     * Sets the value of the t property.
                     * 
                     */
                    public void setT(byte value) {
                        this.t = value;
                    }

                    /**
                     * Gets the value of the td property.
                     * 
                     */
                    public byte getTD() {
                        return td;
                    }

                    /**
                     * Sets the value of the td property.
                     * 
                     */
                    public void setTD(byte value) {
                        this.td = value;
                    }

                    /**
                     * Gets the value of the w property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getW() {
                        return w;
                    }

                    /**
                     * Sets the value of the w property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setW(String value) {
                        this.w = value;
                    }

                    /**
                     * Gets the value of the ftime property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFtime() {
                        return ftime;
                    }

                    /**
                     * Sets the value of the ftime property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFtime(String value) {
                        this.ftime = value;
                    }

                }

            }

        }

    }

}
