//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 02:09:18 PM GMT 
//


package is.hi.vinnsla;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the is.hi.vinnsla package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: is.hi.vinnsla
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nidurstodur }
     * 
     */
    public Nidurstodur createNidurstodur() {
        return new Nidurstodur();
    }

    /**
     * Create an instance of {@link Nidurstodur.AllarStodvar }
     * 
     */
    public Nidurstodur.AllarStodvar createNidurstodurAllarStodvar() {
        return new Nidurstodur.AllarStodvar();
    }

    /**
     * Create an instance of {@link Nidurstodur.AllarStodvar.Vedurstod }
     * 
     */
    public Nidurstodur.AllarStodvar.Vedurstod createNidurstodurAllarStodvarVedurstod() {
        return new Nidurstodur.AllarStodvar.Vedurstod();
    }

    /**
     * Create an instance of {@link Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar }
     * 
     */
    public Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar createNidurstodurAllarStodvarVedurstodSpaStodvar() {
        return new Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar();
    }

    /**
     * Create an instance of {@link Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar.Vedurspa }
     * 
     */
    public Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar.Vedurspa createNidurstodurAllarStodvarVedurstodSpaStodvarVedurspa() {
        return new Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar.Vedurspa();
    }

}
